### ISSUE TITLE
Inline-block

### ISSUE THREAD

**Issue by Riv67** [Riv67/horizontal-nav#1]
@thomasjbradley, I ran into an issue when I put it in Markbot... It looks great and matches the screenshot but Markbot says it’s missing inline-block. Where do I add that? I tried adding it in different places, I was thinking maybe on the h1 but when it’s there I can’t center align the text.

**Comment by thomasjbradley** [comment]
How did you get the `li` tags beside each other on one line?

**Comment by Riv67** [comment]
I used display flex on the nav ul, should I change that to inline-block?

**Comment by thomasjbradley** [comment]
Yeah, unfortunately. When completing this assignment we hadn’t learned `display: flex` yet.

**Comment by Riv67** [comment]
Okay, I’ll try figure it out.
